# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/16331/Documents/GitHub_Projects/xilinx-summer-camp-project/project2/project_v2_RGB2HSV/RGB_LED_v1.srcs/sources_1/ip/csi2_d_phy_rx_0/csi2_d_phy_rx_0.xci
# IP: The module: 'csi2_d_phy_rx_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/16331/Documents/GitHub_Projects/xilinx-summer-camp-project/project2/project_v2_RGB2HSV/RGB_LED_v1.srcs/sources_1/ip/csi2_d_phy_rx_0/hdl/csi2_d_phy_rx.xdc
# XDC: The top module name and the constraint reference have the same name: 'csi2_d_phy_rx_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/16331/Documents/GitHub_Projects/xilinx-summer-camp-project/project2/project_v2_RGB2HSV/RGB_LED_v1.srcs/sources_1/ip/csi2_d_phy_rx_0/csi2_d_phy_rx_0.xci
# IP: The module: 'csi2_d_phy_rx_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/16331/Documents/GitHub_Projects/xilinx-summer-camp-project/project2/project_v2_RGB2HSV/RGB_LED_v1.srcs/sources_1/ip/csi2_d_phy_rx_0/hdl/csi2_d_phy_rx.xdc
# XDC: The top module name and the constraint reference have the same name: 'csi2_d_phy_rx_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
